/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as LoginRouteImport } from './routes/login';
import { Route as FeedRouteImport } from './routes/feed';
import { Route as BrowseRouteImport } from './routes/browse';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username';
import { Route as GamesGameIdRouteImport } from './routes/games/$gameId';
const LoginRoute = LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
});
const FeedRoute = FeedRouteImport.update({
    id: '/feed',
    path: '/feed',
    getParentRoute: () => rootRouteImport,
});
const BrowseRoute = BrowseRouteImport.update({
    id: '/browse',
    path: '/browse',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
    id: '/profile/$username',
    path: '/profile/$username',
    getParentRoute: () => rootRouteImport,
});
const GamesGameIdRoute = GamesGameIdRouteImport.update({
    id: '/games/$gameId',
    path: '/games/$gameId',
    getParentRoute: () => rootRouteImport,
});
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    BrowseRoute: BrowseRoute,
    FeedRoute: FeedRoute,
    LoginRoute: LoginRoute,
    GamesGameIdRoute: GamesGameIdRoute,
    ProfileUsernameRoute: ProfileUsernameRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
